### ISSUE TITLE
create status item with click callback doesn't work for me.

### ISSUE THREAD

**Issue by BelinChung** [MacGapProject/MacGap2#58]
Code
``` javascript
MacGap.StatusItem.create({
    image:"public/menu_bar@2x.png", 
    alternateImage: "public/menu_bar_alter@2x.png",
    onClick: function() { console.log('xxxx') }
 });
```
 Is there any problem?

**Comment by rawcreative** [comment]
Yes, you should not be passing your callback as `onClick: function() { .. }`, it should just be `function() { ... }`, however JavascriptCore for whatever reason discards any function whenever it's inside an object, which is ultimately why it's not working properly, regardless of the syntax error. I've modified the StatusItem.create() method to require the callback be passed as a second param instead of inside the properties object, usage is now:


    var item = MacGap.StatusItem.create({
	      title: 'Title',
	      titleFontSize: 16,
          image:'path/to/image.png', 
          alternateImage: 'path/to/alternateimg.png'
        }, function() { ... });

**Comment by jeff-h** [comment]
Docs updated: http://docs.macgap.com/ref/status-item.html
