### ISSUE TITLE
loading CSS and JS files from index.html

### ISSUE THREAD

**Issue by rsaccon** [MacGapProject/MacGap2#69]
I tried to adapt the index.html and added the files to public folder. But it did not work, files were not found. Is this supposed to work ? If not (yet), any hint were I should start to look into ? Implementing Event handler at the WebViewDelegate  or so ?

**Comment by jeff-h** [comment]
Not sure what's gone wrong for you. If you do a clean checkout of MG2, and directly modify the public/index.html it should work out of the box. No Objective-C coding is required; you should be able to just open the `MG.xcodeproj` file in Xcode and hit the run button.

Otherwise, feel free to stick what you've done up on your Github account and I'll take a look.

**Comment by rsaccon** [comment]
I started from scratch and it worked as expected. Must have been a miss with my asset directories or so. Thanks a lot anyway.
